all: clean

clean:
	rm -f exec1 psh1 forkdemo1 forkdemo2 forkdemo3 \
	      waitdemo1 waitdemo2

exec1: exec1.c
	cc exec1.c -o exec1

psh1: psh1.c
	cc psh1.c -o psh1

forkdemo1: forkdemo1.c
	cc forkdemo1.c -o forkdemo1

forkdemo2: forkdemo2.c
	cc forkdemo2.c -o forkdemo2

forkdemo3: forkdemo3.c
	cc forkdemo3.c -o forkdemo3

waitdemo1: waitdemo1.c
	cc waitdemo1.c -o waitdemo1

waitdemo2: waitdemo2.c
	cc waitdemo2.c -o waitdemo2
