all: clean

clean:
	rm -f exec1 psh1 forkdemo1 forkdemo2

exec1: exec1.c
	cc exec1.c -o exec1

psh1: psh1.c
	cc psh1.c -o psh1

forkdemo1: forkdemo1.c
	cc forkdemo1.c -o forkdemo1

forkdemo2: forkdemo2.c
	cc forkdemo2.c -o forkdemo2
